# **Capítulo 1: Primeiros passos com Python**

Este módulo introdutório é o seu ponto de partida no mundo da análise de dados e finanças com Python.

## **1.1 O que é Python e por que devo aprendê-lo?**

Python é uma linguagem de programação versátil e poderosa, conhecida por sua sintaxe simples e legível. Para profissionais com interesse em programação e análise de dados, especialmente no mercado financeiro, Python se tornou uma ferramenta indispensável. Isso se deve ao seu vasto ecossistema de bibliotecas, que são conjuntos de ferramentas prontas para resolver problemas complexos.

Alguns motivos para aprender Python:

* **É gratuito e de código aberto**;

* **Possui uma curva de aprendizado amigável**, sendo considerada uma das linguagens mais fáceis para iniciantes;

* **Tem uma comunidade enorme e ativa**, o que significa uma quantidade imensa de tutoriais e ajuda disponíveis gratuitamente na internet;

* **É excelente para automatizar rotinas** e sistematizar tarefas repetitivas;

* **É amplamente utilizado no mercado financeiro** e na comunidade acadêmica;

* **Oferece uma quantidade enorme de pacotes (bibliotecas)** para as mais diversas necessidades, desde análise de dados até inteligência artificial;

* **É uma ótima ferramenta para criar relatórios e gráficos profissionais**.

## **1.2 Introdução ao Ambiente Python (Jupyter Notebook)**
Embora seja possível escrever código Python em um simples editor de texto, o trabalho de análise de dados se torna muito mais produtivo com uma ferramenta adequada.  A ferramenta mais popular para isso é o **Jupyter Notebook**.

O Jupyter é uma interface gráfica que facilita muito o dia a dia de trabalho.  Ele permite criar "cadernos" interativos onde você pode:

1. **Escrever e executar código** em blocos, chamados de "células".

2. **Visualizar os resultados** (tabelas, gráficos, etc.) imediatamente abaixo da célula de código.

3. **Escrever texto formatado**, como este que você está lendo, para documentar sua análise.

4. **Testar e experimentar ideias** de forma rápida e organizada. 

## **1.3 Operações Aritméticas**
Python pode ser usado como uma calculadora para realizar operações matemáticas simples. 

In [ ]:
# Adição
print(4 + 5)
# Resultado: 9

# Subtração
print(2 - 3)
# Resultado: -1

# Multiplicação
print(4 * 8)
# Resultado: 32

# Divisão
print(1 / 3)
# Resultado: 0.3333333333333333

# Exponenciação
print(2 ** 5)
# Resultado: 32

# Módulo (resto da divisão)
print(4 % 3)
# Resultado: 1

# Divisão inteira
print(9 // 2)
# Resultado: 4

## **1.4 Criação de Variáveis e Objetos**
Para que nosso trabalho seja útil, precisamos armazenar valores em variáveis. Uma variável é um nome que damos a um espaço na memória do computador onde um valor é guardado.  Em Python, a criação de variáveis é feita com o sinal de igual (`=`).



In [ ]:
# Atribuindo o valor 15 à variável x
x = 15

# Agora, podemos usar 'x' em outras operações
print(x + 5)
# Resultado: 20

print(x * x / 2)
# Resultado: 112.5

# Podemos criar uma nova variável a partir de outra
y = x / 3
print(y)
# Resultado: 5.0

## **1.5 Estruturas de Dados (Tipos Básicos)**
Os objetos que criamos podem ter diferentes tipos, como números, textos ou valores lógicos (verdadeiro/falso). Usamos a função `type()` para verificar o tipo de uma variável

In [ ]:
inteiro = 928
decimal = 182.93
caracter = 'exportação'
logico = True  # Em Python, os valores lógicos são True e False (com letra maiúscula)

print(type(inteiro))
# Resultado: <class 'int'> (inteiro)

print(type(decimal))
# Resultado: <class 'float'> (ponto flutuante/decimal)

print(type(caracter))
# Resultado: <class 'str'> (string/texto)

print(type(logico))
# Resultado: <class 'bool'> (booleano/lógico)

## **1.6 Operadores de Comparação**
Operadores de comparação são usados para comparar valores, e o resultado é sempre um valor lógico: `True` ou `False`. 

* `==` : igual a 
* `!=` : diferente 
* `or`: ou 
* `and`: e 
* `>`, `>=`, `<`, `<=` : maior, maior ou igual, menor, menor ou igual 

Veja alguns exemplos:

In [ ]:
print(1 > 2)
# Resultado: False

print("b" > "a")  # Python compara strings em ordem alfabética
# Resultado: True

print(1 != 2)
# Resultado: True

# Combinando testes lógicos
print((4 > 5) or (1 < 2))  # False ou True
# Resultado: True

print((4 > 5) and (1 < 2)) # False e True
# Resultado: False

## **1.7 Conversões de Tipos de Variáveis**
Às vezes, precisamos converter uma variável de um tipo para outro. Para isso, Python oferece funções de conversão simples.

In [ ]:
# Convertendo texto para número
numero = float("2015")
print(numero)
print(type(numero))
# Resultado: 2015.0, <class 'float'>

# Convertendo número para texto
texto = str(55)
print(texto)
print(type(texto))
# Resultado: '55', <class 'str'>

# Convertendo número para inteiro (remove a parte decimal)
inteiro = int(3.14)
print(inteiro)
# Resultado: 3

# Convertendo valores lógicos para números
print(int(True))
# Resultado: 1
print(int(False))
# Resultado: 0

# Convertendo o tipo de uma variável
x = 10
print(type(x))
x = str(x)
print(type(x))

2015.0
<class 'float'>
55
<class 'str'>
3
1
0
<class 'int'>
<class 'str'>


## **1.8 Vetores com NumPy**
Vetores são sequências de valores de um mesmo tipo, como uma coluna de uma planilha.  Em Python, a ferramenta padrão para trabalhar com vetores numéricos é a biblioteca **NumPy**. Primeiro, precisamos importá-la.

In [ ]:
import numpy as np

Para criar um vetor (chamado de `array` em NumPy), usamos a função `np.array()`.

In [ ]:
vetor_num = np.array([1, 2, 5, 8, 1001])
vetor_chr = np.array(['tipo1', 'tipo2', 'tipo3', 'tipo4'])
vetor_logico = np.array([True, True, False, False])

print(vetor_num)

Para acessar elementos de um vetor, usamos colchetes `[]`. **Atenção**: a contagem em Python começa do zero. O primeiro elemento está na posição `[0]`, o segundo em `[1]`, e assim por diante.

In [ ]:
vetor = np.array([0, 15, 30, 45, 60, 75, 90])

# Mostra o primeiro elemento
print(vetor[0])
# Resultado: 0

# Mostra o segundo elemento
print(vetor[1])
# Resultado: 15

# Selecionando mais de um elemento (o segundo e o sétimo)
print(vetor[[1, 6]])
# Resultado: [15 90]

# Selecionando com base em uma condição lógica
print(vetor[vetor < 20])
# Resultado: [ 0 15]

## **1.9 Matrizes com NumPy**
Matrizes são estruturas com duas dimensões: linhas e colunas.  Elas também são criadas como `arrays` em NumPy.

In [ ]:
# Criando uma matriz a partir de 3 vetores
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# A função np.c_ combina os vetores como colunas
matriz = np.c_[v1, v2, v3]
print(matriz)
# Resultado:
# [[1 4 7]
#  [2 5 8]
#  [3 6 9]]

Para acessar elementos da matriz, usamos `[linha, coluna]`, lembrando que a contagem começa do zero. 

In [ ]:
# Acessando a primeira linha inteira
print(matriz[0, :])
# Resultado: [1 4 7]

# Acessando a segunda coluna inteira
print(matriz[:, 1])
# Resultado: [4 5 6]

# Acessando o elemento na primeira linha e terceira coluna
print(matriz[0, 2])
# Resultado: 7

## **1.10 DataFrames com Pandas**
O **DataFrame** é o tipo de objeto mais importante para análise de dados em Python. Ele representa uma tabela de dados estruturada em linhas e colunas, onde cada coluna pode ter um tipo de dado diferente. A biblioteca para trabalhar com DataFrames é a **Pandas**.

In [ ]:
import pandas as pd

# Criando vetores (listas) para cada coluna
nome = ['João', 'José', 'Maria', 'Joana']
idade = [45, 12, 28, 31]
adulto = [True, False, True, True]
uf = ['DF', 'SP', 'RJ', 'MG']

# Criando o DataFrame a partir de um dicionário
clientes = pd.DataFrame({
    'nome': nome,
    'idade': idade,
    'adulto': adulto,
    'uf': uf
})

print(clientes)

Para ver a estrutura do DataFrame (similar à função `str()` do R), usamos o método `.info()`.

In [ ]:
clientes.info()

## **1.11 Funções**
Uma função é uma sequência de comandos que pode ser reutilizada para executar uma tarefa específica. Python já vem com diversas funções prontas, e podemos adicionar muitas outras através de bibliotecas. Uma função tem um **nome** e recebe **parâmetros** (ou argumentos) entre parênteses.

In [ ]:
# Função para calcular raiz quadrada (da biblioteca NumPy)
raiz_quadrada = np.sqrt(16)
print(raiz_quadrada)
# Resultado: 4.0

# Função para arredondar um número para 2 casas decimais
arredondado = round(5.3499999, 2)
print(arredondado)
# Resultado: 5.35

Para obter ajuda sobre uma função no Jupyter Notebook, digite `?` antes ou depois do nome da função (ex: `?round` ou `round?`) e execute a célula. 

Algumas funções estatísticas básicas são aplicadas como "métodos" diretamente nos objetos Pandas ou NumPy.

In [ ]:
dados_numericos = pd.Series([10, 20, 30, 40, 50])

print("Soma:", dados_numericos.sum())
print("Média:", dados_numericos.mean())
print("Variância:", dados_numericos.var())
print("Mediana:", dados_numericos.median())
print("Resumo Estatístico:\n", dados_numericos.describe())

## **1.12 Pacotes (Bibliotecas)**
Bibliotecas são conjuntos de funções que expandem as capacidades do Python.  Para usá-las, seguimos dois passos:

1. **Instalação**: Feita apenas uma vez, através de um terminal de comando, usando o gerenciador de pacotes pip. Por exemplo:

In [ ]:
pip install pandas
pip install numpy

2. **Importação**: Feita no início de cada script ou notebook, para carregar a biblioteca na memória e poder usar suas funções. 

In [ ]:
import pandas as pd
import numpy as np

## **1.13 Exercícios**
Vamos aplicar o que aprendemos. Você recebeu uma lista com os retornos diários de um ativo financeiro.

Sua tarefa é usar as ferramentas das bibliotecas **NumPy** e **Pandas** para calcular as seguintes estatísticas:

1.  Um **resumo estatístico completo** (contagem, média, desvio padrão, mínimo, máximo e os quartis).
2.  O valor do **desvio padrão** (amostral) calculado separadamente.

**Dica:** Lembre-se que as `Series` do Pandas (que podem ser criadas a partir de um array NumPy) possuem o método `.describe()` que é perfeito para o resumo. Para o desvio padrão, use o método `.std()`.

In [ ]:
#import


# Dados do exercício
retornos = np.array([0.0102, 0.00186, -0.00635, 0.0193,
                     0.00203, -0.01846, 0.00434,
                     -0.01256, -0.00944, -0.00087])

# 1. Crie uma Pandas Series a partir do array 'retornos'


# 2. Calcule e imprima o resumo estatístico


# 3. Calcule e imprima o desvio padrão